server:
  port: 9766
eureka:
  #instance:
    #hostname: gateway
  client:
    service-url:
      defaultZone: http://discovery:9761/eureka/
spring:
  application:
    name: api-gateway

management:
  security:
    enabled: false
security:
  basic:
    enabled: false

zuul:
  ignored-services: microservice-provider-user                       # 需要忽视的服务(配置后将不会被路由)
  prefix: /api
  add-host-header: true              #避免重定向暴露真实服务器地址
  routes:
    monitor-server:                  # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /monitor/**               # 想要映射到的路径
      strip-prefix: false
     # service-id: monitor-server     # Eureka中的serviceId
    user:
      path: /user/**
      #strip-prefix: false
      service-id: app-manage


