server:
  port: 8080

spring:
  datasource:
   url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.16.0.104
    database: 3
  application:
    name: auth-server
  cache:
    type: redis
eureka:
  client:
    service-url:
     defaultZone: http://discovery:9761/eureka/
#  jpa:
#    hibernate:
#      ddl-auto: none

#logging:
#  level:
#    jdbc: error
#    jdbc.sqltiming: info

security:
  oauth2:
    resource:
      filter-order: 3

custom:
  security:
    oauth2:
      signingKey: robustel
    userDetails:
      usersByUsernameQuery: select user_name,login_pwd,user_id
         from tbs_pl_user_base_info where state in ('1') and (login_account=:username or email=:username)
  redis:
    cache:
     expires:
        user: 300