server:
  port: 8080

spring:
  datasource:
   url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.16.0.104
    database: 0
  application:
    name: auth-server
eureka:
  client:
    service-url:
     defaultZone: http://discovery:9761/eureka/
#  jpa:
#    hibernate:
#      ddl-auto: none

#logging:
#  level:
#    jdbc: error
#    jdbc.sqltiming: info

security:
  oauth2:
    resource:
      filter-order: 3
auth:
  security:
     oauth2:
      signingKey: robustel