spring:
    application:
        name: monitor-server
    boot:
        admin:
          routes:
            endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
          turbine:
            #clusters: jscloud
            location: monitor-server
          context-path: /monitor
server:
    port: 9764
    #context-path: /monitor
#security:
    #user:
        #name: whb
        #password: 123456
        #role: USER

eureka:
     instance:
        preferIpAddress: true
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://discovery:9761/eureka/
management:
  security:
    enabled: false
security:
  basic:
    enabled: false

#turbine:
  #cluster-name-expression: default
  #combine-host-port: true