server:
  port: 9781
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:9761/eureka/
management:
  security:
    enabled: false
security:
  basic:
    enabled: false